### ISSUE TITLE
关于project里的淘宝项目

### ISSUE THREAD

**Issue by houkensjtu** [DreaMer963/crawler#1]
您好！感谢你分享自己的项目代码。
有个小问题，project里的淘宝项目为什么特意做成了一个class呢？看代码中也只有几个函数，感觉直接定义函数也一样。是有什么意图的吗？

谢谢！

**Comment by xudong963** [comment]
因为目前的代码只是爬取了很少的信息，如果要爬取更多的信息，会接着往这个类中添加函数。
